[package]
name = "charon"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
acme-lib = "0.8.1"
ahash = "0.6.2"
arc-swap = "1.2.0"
chrono = "0.4.19"
color-eyre = { version = "0.5.10", default-features = false }
eyre = "0.6.5"
futures-util = "0.3.9"
hyper = { version = "0.14.2", features = ["full"] }
hyperx = "1.3.0"
log = { version = "0.4.11", features = ["release_max_level_info"] }
parking_lot = "0.11.1"
pin-project = "1.0.3"
pretty_env_logger = "0.4.0"
rustls = { version = "0.19.0", default-features = false }
serde = { version = "1.0.118", features = ["derive"] }
tokio = { version = "1.0.1", features = ["macros", "rt-multi-thread"] }
tokio-rustls = "0.22.0"
toml = "0.5.8"
tower = "0.4.1"

[profile.release]
lto = true
panic = "abort"
