[package]
name = "charon"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
acme-lib = "0.8.1"
ahash = "0.4.5"
arc-swap = "0.4.7"
chrono = "0.4.15"
color-eyre = "0.5.5"
eyre = "0.6.0"
futures-util = "0.3.5"
hyper = "0.13.8"
hyperx = "1.1.0"
parking_lot = "0.11.0"
pin-project = "0.4.23"
rustls = "0.18.1"
serde = { version = "1.0.116", features = ["derive"] }
tokio = { version = "0.2.22", features = ["macros", "rt-threaded"] }
tokio-rustls = "0.14.1"
toml = "0.5.6"
tower = "0.3.1"
tracing = "0.1.19"
tracing-subscriber = "0.2.12"

[profile.release]
lto = true
panic = "abort"
