[package]
name = "charon"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
acme-lib = "0.8.1"
ahash = "0.6.1"
arc-swap = "1.0.0"
chrono = "0.4.19"
color-eyre = { version = "0.5.8", default-features = false }
eyre = "0.6.3"
futures-util = "0.3.8"
hyper = "0.13.9"
hyperx = "1.2.0"
log = "0.4.11"
parking_lot = "0.11.1"
pin-project = "1.0.2"
pretty_env_logger = "0.4.0"
rustls = { version = "0.19.0", default-features = false }
serde = { version = "1.0.117", features = ["derive"] }
tokio = { version = "0.2.22", features = ["macros", "rt-threaded"] }
tokio-rustls = "0.15.0"
toml = "0.5.7"
tower = "0.3.1"

[profile.release]
lto = true
panic = "abort"
